# Generated by Django 6.1.1 on 2026-09-14 16:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Set EITHER percentage OR flat amount', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Flat ₹ off — set EITHER amount OR percentage', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap for percentage coupons, e.g. "50% up to ₹100"', max_digits=8, null=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurants/')),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('cuisine_type', models.CharField(choices=[('pizza', 'Pizza'), ('burger', 'Burger'), ('indian', 'Indian'), ('chinese', 'Chinese'), ('dessert', 'Dessert'), ('sushi', 'Sushi'), ('thali', 'Thali'), ('rolls', 'Rolls'), ('multi', 'Multi-Cuisine')], default='multi', max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, help_text='0.0 – 5.0', max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))])),
                ('delivery_time', models.PositiveIntegerField(default=30, help_text='Average delivery time in minutes')),
                ('min_order', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('offer_text', models.CharField(blank=True, help_text='Offer banner shown on the card, e.g. "40% OFF up to ₹80"', max_length=100)),
                ('is_promoted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('opening_time', models.TimeField(blank=True, default=None, null=True)),
                ('closing_time', models.TimeField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['-is_promoted', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank if not discounted', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_veg', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))])),
                ('preparation_time', models.PositiveIntegerField(default=20, help_text='Minutes')),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='core.category')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='core.restaurant')),
            ],
            options={
                'verbose_name_plural': 'Dishes',
                'ordering': ['-is_bestseller', 'name'],
            },
        ),
    ]
