# Generated by Django 6.1.1 on 2026-09-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('owner', 'Restaurant Owner'), ('admin', 'Admin')], default='customer', max_length=10),
        ),
    ]
